name: Build workflow

on:
  push:
    branches: ["release"]

  workflow_dispatch:

concurrency:
  group: "build-release"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build
        env:
          BASE_PATH:

      - name: Move to release branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          publish_branch: build

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d-%H-%M')"

      - name: Switch branch
        uses: actions/checkout@v4
        with:
          ref: build

      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: "zip"
          filename: "rgv-floodmap.zip"
          exclusions: "*.git* /*node_modules/* .editorconfig"

      - name: Upload Release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "rgv-floodmap.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.date.outputs.date }}
